FROM ubuntu:14.04.5

RUN dpkg --add-architecture i386
RUN apt-get update --fix-missing

RUN apt-get install -f -yy \
  asciidoctor \
  autoconf \
  automake \
  ccache \
  clang \
  libtool:i386 \
  pkg-config \
  graphviz \
  kmod \
  make \
  mscgen \
  ruby-dev \
  xsltproc \
  git \
  iproute2 \
  python-pip \
  gcc:i386 \
  g++:i386 \
  cpp:i386 \
  gcc-4.8:i386 \
  g++-4.8:i386 \
  libc6:i386 \
  libc6-dev:i386 \
  libconfig-dev:i386 \
  libgcc1:i386 \
  libssl-dev:i386 \
  libssl1.0.0:i386 \
  linux-libc-dev:i386 \
  zlib1g-dev:i386 \
