FROM centos:7

RUN yum update -y

RUN yum install -y \
	https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum install -y \
	autoconf \
	automake \
	clang \
	CUnit-devel \
	curl \
	doxygen \
	dpdk \
	dpdk-devel \
	gcc \
	gcc-c++ \
	git-core \
	graphviz \
	kmod \
	libatomic \
	libconfig-devel \
	libtool \
	make \
	net-tools \
	openssl-devel \
	pkgconfig \
	sudo
